### ISSUE TITLE
Issue with duration

### ISSUE THREAD

**Issue by SigridBeWa** [BeverCRM/PCF-EditableTable#20]
When creating a new row of the record type time entry the duration field is not updated until after saving. Therefor some value needs to be added in order for it to be possible to save. I tried to not have the duration field mandatory but still got the same error. 

https://github.com/BeverCRM/PCF-EditableTable/assets/137784064/a5eb4a92-ca59-4a74-abd6-8175cb7ccc42

**Comment by emibanana** [comment]
Pretty sure you shouldn't make duration as required field, this is the dataverse setting not the PCF control, right?

**Comment by RubenAghajanyan** [comment]
@SigridBeWa,

Time Entry duration field calculation is an out-of-the-box feature implemented by MS. Unfortunately, we don't have access to this functionality from the editable grid. 

In the new editable grid version, we will enable custom JS rules. One possible solution could be to manually implement a JS rule that will calculate duration based on start and end dates on field change

We'll keep this issue open to track the progress.

Let me know if you'll have further questions.

**Comment by SigridBeWa** [comment]
Hi Ruben,

Thanks for your reply. Do you have any plans for when this new editable grid will be released? And is the offline capabilities included in that release?

Best regards,
Sigrid Berg Wallin

***@***.***


Sigrid Berg Wallin
Product Owner, Lead to Cash
Mobile: +46 761 126596
***@***.******@***.***>
Contact me on Teams: ***@***.***

Alfa Laval Technologies AB
Address - 221 00 Lund - Sweden
Visit: Rudeboksvägen 1 - Lund - Sweden
Registration number: 556016-8642
Tel switchboard: +46 46 36 6500
https://www.alfalaval.com<http://www.alfalaval.com/> - ***@***.******@***.***>
This e-mail is intended solely for the use of the individual or entity to whom it is addressed and its content shall be regarded
as confidential unless explicitly stated otherwise. If you have received this e-mail by mistake, please notify the sender
immediately by e-mail and delete this e-mail from your system. Personal data and email will be handled in accordance with
the Alfa Laval Privacy Policy<https://www.alfalaval.com/privacy>.



Classified by Alfa Laval as: Business

**Comment by RubenAghajanyan** [comment]
Hi Sigrid,

The new version which will be released within the next month will support offline mode.

The premium version which will be released in the next 2-3 months will have JavaScript functions. By using that functions you can write a rule to calculate duration from the start date and end date.

**Comment by RubenAghajanyan** [comment]
@SigridBeWa,

Closing this bug as per our discussion.
