### ISSUE TITLE
Error "Time can not exceed 24"

### ISSUE THREAD

**Issue by SigridBeWa** [BeverCRM/PCF-EditableTable#21]
For time entries on the current day I get this error that the time can not exceed 24h, even though I'm not exceeding 24h. 

https://github.com/BeverCRM/PCF-EditableTable/assets/137784064/1e67b924-d3a1-4942-88a8-4b3ebfee05c5

**Comment by RubenAghajanyan** [comment]
@SigridBeWa ,

Any updates here? Did you try to put the same time-entry values using the main form instead of the editable grid to check whether the error persists?

**Comment by HasmikMn** [comment]
Hello @SigridBeWa, 

We are happy to inform you that the new version of Editable Table is now available!

**Comment by SigridBeWa** [comment]
Hi Hasmik,

I'm happy to hear! I will test it immediately.

Best regards,
Sigrid Berg Wallin

***@***.***


Sigrid Berg Wallin
Product Owner, Lead to Cash
Mobile: +46 761 126596
***@***.******@***.***>
Contact me on Teams: ***@***.***

Alfa Laval Technologies AB
Address - 221 00 Lund - Sweden
Visit: Rudeboksvägen 1 - Lund - Sweden
Registration number: 556016-8642
Tel switchboard: +46 46 36 6500
https://www.alfalaval.com<http://www.alfalaval.com/> - ***@***.******@***.***>
This e-mail is intended solely for the use of the individual or entity to whom it is addressed and its content shall be regarded
as confidential unless explicitly stated otherwise. If you have received this e-mail by mistake, please notify the sender
immediately by e-mail and delete this e-mail from your system. Personal data and email will be handled in accordance with
the Alfa Laval Privacy Policy<https://www.alfalaval.com/privacy>.



Classified by Alfa Laval as: Business

**Comment by RubenAghajanyan** [comment]
@SigridBeWa,

Closing this bug as per our discussion.
