### ISSUE TITLE
error saving existing product

### ISSUE THREAD

**Issue by empresawebs** [BeverCRM/PCF-EditableTable#36]
Hi,
in the offers, when selecting an existing product and saving, this error appears:
![image001](https://github.com/BeverCRM/PCF-EditableTable/assets/57011515/6b44e0b1-9b4f-492e-953f-67f13ea67c6a)
![image009](https://github.com/BeverCRM/PCF-EditableTable/assets/57011515/19c29861-1c56-452c-88b0-34e5e158a28f)
![image011](https://github.com/BeverCRM/PCF-EditableTable/assets/57011515/29a1d467-960c-4f6f-8d43-0a958478ee47)
![image012](https://github.com/BeverCRM/PCF-EditableTable/assets/57011515/8ff76358-321e-4379-a3ec-a87381b204df)

specify a default unit with sales unit

**Comment by empresawebs** [comment]
Hi @RubenAghajanyan,
If I delete your component in the offer form, it works correctly.
With the standard form it works fine but with yours it doesn't.
It seems like a problem with your component.
Do you know what it could be?
Thanks

**Comment by RubenAghajanyan** [comment]
@empresawebs,

Okey. It means you have some fields (Unit or Unit Group) in the form, and you don't have these fields in the editable grid. If it's working fine from the form, means you are setting that field (Unit or Unit Group) values in the form (or you have a JavaScript which is setting values for that field automatically).

For example, if I'll try to save a Sales Order product without specifying the unit, it will give me this error. 

![image](https://github.com/BeverCRM/PCF-EditableTable/assets/10652791/a9142e6f-7411-4326-902c-117bd7998ea4)


So, try to see what fields you have in the form (should be something related to unit or/and unit group) and bring that fields in the editable grid. Put the same value in the editable grid, that you're putting in the form..

**Comment by empresawebs** [comment]
Hello, I have added the unit field in the view to be able to fill it in and it works.
Thanks!
