### ISSUE TITLE
Not able to import solution

### ISSUE THREAD

**Issue by jacksonasneed** [BeverCRM/PCF-EditableTable#38]
I rarely use PCFs so this could be very easily be user error, but whenever I down a zip of the repository and attempt to import it as a solution into my environment I get the following error: 
"The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and [Content_Types].xml. Customization files exported from previous versions of Microsoft Dynamics 365 are not supported."

I'm guessing the issue is with the version of D365 or PCF framework used to create the project. Would appreciate any insight.

**Comment by RubenAghajanyan** [comment]
Closing this bug as no further update was provided.
