### ISSUE TITLE
Tabbing order

### ISSUE THREAD

**Issue by PowellPowell** [BeverCRM/PCF-EditableTable#63]
Hi,

If it's possible, tabbing order should be added. Now it is only possible to use the arrow keys and not the tab key.

**Comment by RubenAghajanyan** [comment]
Hey @PowellPowell,

Unfortunately no. And it has a reason. Tabs are used to go between form fields and go between form sub-grids. So, we can't use a tab inside the editable sub-grid. For navigating in sub-grid we need to use arrow keys and this is Microsoft setup (If you try the standard editable grid of Microsoft, tabs will not work there too. You need to use arrow keys).

**Comment by RubenAghajanyan** [comment]
Closed. Required functionality isn't possible to add.
